---
- hosts: debianservers
  become: true
  tasks:
  - name: Copy a new file into place, backing up the original if it differs from the copied version
    copy:
      src: ./borrame.ya
      dest: /tmp/
      owner: root
      group: root
      mode: '0644'
      backup: yes
# Usage: ansible-playbook copy_example.yml -v -K
