#- name: Update repositories cache and install "foo" package
#  apt:
#    name: foo
#    update_cache: yes

#- name: Install apache httpd but avoid starting it immediately (state=present is optional)
#  apt:
#    name: apache2
#    state: present
#  environment:
#    RUNLEVEL: 1
#
#- name: Remove "foo" package
#  apt:
#    name: foo
#    state: absent
#
#- name: Install the package "foo"
#  apt:
#    name: foo

- hosts: all
  become: true
  tasks:
  - name: Check disk space
    shell: pydf -h

#- name: Install the version '1.00' of package "foo"
#  apt:
#    name: foo=1.00
#
#- name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
#  apt:
#    name: nginx
#    state: latest
#    default_release: squeeze-backports
#    update_cache: yes
#
#- name: Install latest version of "openjdk-6-jdk" ignoring "install-recommends"
#  apt:
#    name: openjdk-6-jdk
#    state: latest
#    install_recommends: no
#
#- name: Upgrade all packages to the latest version
#  apt:
#    name: "*"
#    state: latest
#
#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist
#
#- name: Run the equivalent of "apt-get update" as a separate step
#  apt:
#    update_cache: yes
#
#- name: Pass options to dpkg on run
#  apt:
#    upgrade: dist
#    update_cache: yes
#    dpkg_options: 'force-confold,force-confdef'
#
#- name: Install a .deb package
#  apt:
#    deb: /tmp/mypackage.deb
#
#- name: Install the build dependencies for package "foo"
#  apt:
#    pkg: foo
#    state: build-dep
#
#- name: Install a .deb package from the internet.
#  apt:
#    deb: https://example.com/python-ppq_0.1-1_all.deb
#
#- name: Remove useless packages from the cache
#  apt:
#    autoclean: yes
#
#- name: Remove dependencies that are no longer required
#  apt:
#    autoremove: yes
